services:
  - type: web
    name: bst-backend
    env: node
    repo: https://github.com/HarshYadv5554/Harsh_BST.git
    branch: main
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start

  - type: static
    name: bst-frontend
    repo: https://github.com/HarshYadv5554/Harsh_BST.git
    branch: main
    rootDir: frontend
    # Ensure devDependencies (like Vite) are installed during the build
    buildCommand: npm install --include=dev && npm run build
    publishPath: dist
